# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      yarn global add @vue/cli
      cd ~
      git clone https://github.com/xx745/cellular-automaton-vuejs-2
      cd cellular-automaton-vuejs-2
      yarn install

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
